### ISSUE TITLE
is this project abandoned/DOA?

### ISSUE THREAD

**Issue by naterkane** [crm-js/angular-schema-form-typeahead#1]

**Comment by hepr** [comment]
Hi,

No it just was not finished (doc, test, ...)

Herve

**Comment by vicary** [comment]
I found this way more better than `dynamic-select` when working with large data sets.

The template code looks like ready, any ETC?

**Comment by hepr** [comment]
Hi,

I will push today my code for example. it's not perfect but it work for me :-)

Regards,

Herve

**Comment by hepr** [comment]
Hi,

I push example today
